[tool.isort]
profile = "black"
force_alphabetical_sort = true
force_single_line = true
lines_between_sections = 0

[tool.black]
# when set to 120, black will split at column 121
line-length = 119
target-version = ['py33']
skip-string-normalization = true

[tool.flake8]
max-line-length = 120
